### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by NJLiChaoLong** [icuxika/IMFrameworkFX#1]
环境：jdk16，javafx17,gradle7.3.1
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "field" is null
	at com.jfoenix.skin.JFXTextAreaSkin.createPromptNode(JFXTextAreaSkin.java:101)
	at com.jfoenix.skin.JFXTextAreaSkin.lambda$new$1(JFXTextAreaSkin.java:42)
	at com.jfoenix.skin.PromptLinesWrapper.init(PromptLinesWrapper.java:89)
	at com.jfoenix.skin.JFXTextAreaSkin.<init>(JFXTextAreaSkin.java:42)
	at com.jfoenix.control.JFXTextArea.createDefaultSkin(JFXTextArea.java:43)
	at javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)

**Comment by icuxika** [comment]
@NJLiChaoLong 请问你是什么操作系统呢，我在macOS上分别设置JAVA_HOME指向jdk15、16、17，然后执行`./gradlew run`都可以成功运行。

**Comment by icuxika** [comment]
@NJLiChaoLong 在Windows11下cmd中，set JAVA_HOME=Oracle jdk 17主目录，然后执行`gradlew.bat run`，也可以成功运行，你试下Java17呢，实际上项目配置已经使用17了，README一直没有更新，你目前使用的jdk16具体版本是哪个呢？

**Comment by NJLiChaoLong** [comment]
jdk16.0.2 windows 10，之前是启动Launcher类，报错。如果直接执行 gradlew.bat run，可以成功运行。
